{
  "debianbug": 599739,
  "description": "The audioop module in Python 2.7 and 3.2 does not verify the relationships between size arguments and byte string lengths, which allows context-dependent attackers to cause a denial of service (memory corruption and application crash) via crafted arguments, as demonstrated by a call to audioop.reverse with a one-byte string, a different vulnerability than CVE-2010-1634.",
  "releases": {
    "bullseye": {
      "fixed_version": "2.7-1",
      "repositories": {
        "bullseye": "2.7.18-6"
      },
      "status": "resolved",
      "urgency": "low"
    },
    "buster": {
      "fixed_version": "2.7-1",
      "repositories": {
        "buster": "2.7.16-2+deb10u1"
      },
      "status": "resolved",
      "urgency": "low"
    },
    "sid": {
      "fixed_version": "2.7-1",
      "repositories": {
        "sid": "2.7.18-6"
      },
      "status": "resolved",
      "urgency": "low"
    },
    "stretch": {
      "fixed_version": "2.7-1",
      "repositories": {
        "stretch": "2.7.13-2+deb9u3",
        "stretch-security": "2.7.13-2+deb9u4"
      },
      "status": "resolved",
      "urgency": "low"
    }
  },
  "scope": "local"
}