{
  "affected_release": null,
  "package_state": [
    {
      "product_name": "Red Hat Enterprise Linux 7",
      "fix_state": "Out of support scope",
      "package_name": "python-pillow",
      "cpe": "cpe:/o:redhat:enterprise_linux:7"
    },
    {
      "product_name": "Red Hat Enterprise Linux 8",
      "fix_state": "Not affected",
      "package_name": "python-pillow",
      "cpe": "cpe:/o:redhat:enterprise_linux:8"
    },
    {
      "product_name": "Red Hat Quay 3",
      "fix_state": "Affected",
      "package_name": "quay-registry-container",
      "cpe": "cpe:/a:redhat:quay:3::el7"
    }
  ],
  "threat_severity": "Moderate",
  "public_date": "2021-02-28T00:00:00Z",
  "bugzilla": {
    "description": "CVE-2021-25291 python-pillow: out-of-bounds read in TiffReadRGBATile in TiffDecode.c",
    "id": "1934692",
    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1934692"
  },
  "cvss": {
    "cvss_base_score": "",
    "cvss_scoring_vector": "",
    "status": ""
  },
  "cvss3": {
    "cvss3_base_score": "7.5",
    "cvss3_scoring_vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
    "status": "draft"
  },
  "iava": "",
  "cwe": "CWE-125",
  "statement": "This issue did not affect the versions of python-pillow as shipped with Red Hat Enterprise Linux 8 as they did not include the vulnerable code, which was introduced in a newer upstream version than what what shipped.\nDisable the invoice generation feature to mitigate this vulnerability in Red Hat Quay.",
  "acknowledgement": "",
  "name": "CVE-2021-25291",
  "document_distribution": "",
  "details": [
    "An issue was discovered in Pillow before 8.1.1. In TiffDecode.c, there is an out-of-bounds read in TiffreadRGBATile via invalid tile boundaries."
  ],
  "references": null
}