{
  "debianbug": 969367,
  "description": "An issue was discovered in Django 2.2 before 2.2.16, 3.0 before 3.0.10, and 3.1 before 3.1.1 (when Python 3.7+ is used). FILE_UPLOAD_DIRECTORY_PERMISSIONS mode was not applied to intermediate-level directories created in the process of uploading files. It was also not applied to intermediate-level collected static directories when using the collectstatic management command.",
  "releases": {
    "bullseye": {
      "fixed_version": "2:2.2.16-1",
      "repositories": {
        "bullseye": "2:2.2.19-1"
      },
      "status": "resolved",
      "urgency": "not yet assigned"
    },
    "buster": {
      "nodsa": "Fix along in future DSA",
      "nodsa_reason": "postponed",
      "repositories": {
        "buster": "1:1.11.29-1~deb10u1",
        "buster-security": "1:1.11.29-1~deb10u1"
      },
      "status": "open",
      "urgency": "not yet assigned"
    },
    "sid": {
      "fixed_version": "2:2.2.16-1",
      "repositories": {
        "sid": "2:2.2.19-1"
      },
      "status": "resolved",
      "urgency": "not yet assigned"
    },
    "stretch": {
      "fixed_version": "0",
      "repositories": {
        "stretch": "1:1.10.7-2+deb9u9",
        "stretch-security": "1:1.10.7-2+deb9u11"
      },
      "status": "resolved",
      "urgency": "unimportant"
    }
  },
  "scope": "local"
}