{
  "ID": "pyup.io-37326",
  "Advisory": "Django 1.11.23 fixes the following security issue in 1.11.22: CVE-2019-14232.",
  "Cve": "CVE-2019-14232",
  "Specs": [
    "==1.11.22"
  ],
  "v": "==1.11.22"
}
