{
  "ID": "pyup.io-39521",
  "Advisory": "Django 3.1.6 fixes a security issue with severity \"low\" and a bug in 3.1.5 (CVE-2021-3281).",
  "Cve": "CVE-2021-3281",
  "Specs": [
    "==3.1.5"
  ],
  "v": "==3.1.5"
}
